### PR TITLE
allowing postcss plugins

### PR DESCRIPTION
**Pull request by chrisdugne**
Hello, 
here are small updates I use on my project, upgrading the `v1` using postcss

- #35 added option to add any array of postcss plugins (`@value` for example)

### CODE REVIEW

**Comment by ShaunSpringer** [comment]
This would be a useful feature for me as well!

**Comment by indooorsman** [comment]
v2.4.0 has supported custom `filter`

**Comment by mcmillion** [comment]
The problem that I was running into that led me was trying to get CSS modules working with nesting. No combination of tweaking things would get it to work until I tried @chrisdugne's fork that allows for using postcss plugins.

**Comment by chrisdugne** [comment]
> v2.4.0 has supported custom `filter`

ok, nice; I removed the filter update from this PR, And I'll test it on my side, then close #34

This PR still updates `v1` to allow postcss plugins though

**Pull request closed without merging**
